# AppVeyor configuration file
environment:
  nodejs_version: "8"

init:
  - git config --global core.autocrlf true

install:
  ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

test_script:
  - node --version
  - npm test


