# AppVeyor configuration file
environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm ci

test_script:
  - node --version
  - npm --version
  - nvm --version
  - npm testwin

build: off

